# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20171107_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='city_name',
            field=models.CharField(default='City name', max_length=50),
            preserve_default=False,
        ),
    ]
