# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0003_alert_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='city_name',
            field=models.CharField(max_length=50, verbose_name='City Name'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set([('user_id', 'city_id')]),
        ),
    ]
